name: Release WordPress Plugin

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Plugin Zip
      run: zip -r plugin-update-test.zip .
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./plugin-update-test.zip
        asset_name: plugin-update-test.zip
        asset_content_type: application/zip
